import Head from "next/head";

import { Layout } from "../components/Layout";
import { MainSection } from "../components/Section/MainSection";

import type { NextPage } from "next";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>My Template</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Layout>
        <MainSection />
      </Layout>
    </>
  );
};

export default Home;
