import { useEffect } from "react";

import Head from "next/head";
import { useRecoilValue, useSetRecoilState } from "recoil";

import { Layout } from "../components/Layout";
import { MainSection } from "../components/Section/MainSection";
import { cardListState } from "../store/cardListState";
import { useCardList } from "../utils/hooks/useCardList";

import type { NextPage } from "next";

const Home: NextPage = () => {
  const cardList = useRecoilValue(cardListState);
  const [data] = useCardList();
  const setCardList = useSetRecoilState(cardListState);

  useEffect(() => {
    setCardList(data);
  }, [data]);
  return (
    <>
      <Head>
        <title>My Template</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Layout>
        <MainSection cardList={cardList} />
      </Layout>
    </>
  );
};

export default Home;
